# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCurrency' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
    use_modular_headers!

  # Pods for MyCurrency

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Analytics'
pod 'Fabric', '~> 1.10.2'
pod 'Crashlytics', '~> 3.14.0'



  # Network
pod 'GooglePlaces'
pod 'Moya', '~> 14.0.0'
pod 'IPAPI'
# pod 'Kingfisher'
# pod 'StompClientLib'

 # Database + Mapping
pod 'ObjectMapper', '~> 3.1'
pod 'SwiftKeychainWrapper'

# UI
pod 'SwiftTheme'
pod 'SnapKit', '~> 4.0.0'
pod 'NVActivityIndicatorView'
pod 'lottie-ios'
pod 'Kingfisher'

end
